### ISSUE TITLE
Wrong project path in go.mod file

### ISSUE THREAD

**Issue by Wheart** [go-chef/chef#148] opened 2020-01-17 14:32 UTC
While project was forked, project path in go.mod is left unchanged, causing errors in module-enabled projects.

**Comment by MarkGibbons** [comment] 2020-01-18 14:42
Thank you very much for the bug report.  Could you confirm the issue is fixed now?

**Comment by Wheart** [comment] 2020-01-20 08:44
Release 0.8.0 works OK :) Thank you very much!

**Comment by MarkGibbons** [comment] 2020-01-21 19:56
Cool

**Closed by MarkGibbons** 2020-01-21 19:56 UTC
